name: click_charger_server
description: Server for Click Charger.
version: 0.4.5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dotenv: ^3.0.0
  googleapis_auth: ^1.1.0
  http: ^0.13.3
  json_annotation: ^4.0.0
  pubspec_parse: ^1.0.0
  shelf: ^1.1.4
  shelf_router: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^4.0.0
  pedantic: ^1.9.0
  test: ^1.17.4
