name: Dart
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: google/dart
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Secrets
        env:
          DOTENV: ${{ secrets.DOTENV }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          printf "%s" "$DOTENV" > .env
          printf "%s" "$SERVICE_ACCOUNT_JSON" > service-account.json
      
      - name: Install Dependencies
        run: dart pub get

      - name: Run tests
        run: dart test