name: Dart
on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: google/dart
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Secrets
        env:
          DOTENV: ${{ secrets.DOTENV }}
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        run: |
          printf "%s" "$DOTENV" > .env
          printf "%s" "$FIREBASE_SERVICE_ACCOUNT_JSON" > firebase-service-account.json
          printf "%s" "$GOOGLE_PLAY_SERVICE_ACCOUNT_JSON" > google-play-developer-service-account.json
      
      - name: Install Dependencies
        run: dart pub get

      - name: Run tests
        run: dart test